### ISSUE TITLE
Invalid Login on a new instance of guacamole

### ISSUE THREAD

**Issue by ovizii** [flcontainers/guacamole#142]
Following up on this issue here: https://github.com/flcontainers/guacamole/issues/135 

Here is what I did:

```
sudo su
mkdir /docker/guacamole 
chown -R 1000:root /docker/guacamole
chmod -R 770 /docker/guacamole
```

This is my docker-compose.yml (slightly edited out some details like URL). Please note that I did not manually create the mapped volume folders. Also, UID 1000 is the user which I use to edit these files and folders so it should have access permissions.

```
services:

# https://github.com/flcontainers/guacamole
  guacamole:
    image: flcontainers/guacamole:1.5.5
    container_name: guacamole
    hostname: guacamole
    networks:
      guacamole:
        ipv4_address: 192.168.191.110
      traefik_guacamole:
    restart: "no"
    cpus: 1
    mem_limit: 2G
    volumes:
      - './data:/config'
      - './shared-folder:/tmp/shared-folder'
      - '/usr/share/fonts:/usr/share/fonts:ro'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      TZ: 'Europe/Berlin'
#      EXTENSIONS: 'auth-duo,auth-quickconnect'
    labels:
      # enable Traefik
      - traefik.enable=true
      # Network
      - traefik.docker.network=traefik_guacamole
      # Router
      - traefik.http.routers.guacamole.tls=true
      - traefik.http.routers.guacamole.entrypoints=websecure
      - traefik.http.routers.guacamole.rule=Host(`console.domain.tld`)
      - traefik.http.routers.guacamole.middlewares=secHeaders@file
      - traefik.http.routers.guacamole.service=guacamole
      # Service
      - traefik.http.services.guacamole.loadbalancer.server.port=8080
      - traefik.http.services.guacamole.loadbalancer.server.scheme=http

networks:

  guacamole:
    name: guacamole
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.191.108/30
          gateway: 192.168.191.109
    driver_opts:
      parent: vmbr1.124
    external: false


  traefik_guacamole:
    external: true
    internal: true
    name: traefik_guacamole
```

I then did a `docker compose up -d` and this is what happened: 

- the images got downloaded

Here are the docker logs:

```
guacamole  | Creating db password
guacamole  | Running startup scripts
guacamole  | Preparing Config Folder
guacamole  | Init DB Check
guacamole  | Post startup DB scripts
guacamole  | Guacamole client waiting for DB
guacamole  | The files belonging to this database system will be owned by user "postgres".
guacamole  | This user must also own the server process.
guacamole  |
guacamole  | The database cluster will be initialized with locales
guacamole  |   COLLATE:  C
guacamole  |   CTYPE:    C.UTF-8
guacamole  |   MESSAGES: C
guacamole  |   MONETARY: C
guacamole  |   NUMERIC:  C
guacamole  |   TIME:     C
guacamole  | The default database encoding has accordingly been set to "UTF8".
guacamole  | The default text search configuration will be set to "english".
guacamole  |
guacamole  | Data page checksums are disabled.
guacamole  |
guacamole  | fixing permissions on existing directory /config/postgres ... ok
guacamole  | creating subdirectories ... ok
guacamole  | selecting dynamic shared memory implementation ... posix
guacamole  | selecting default max_connections ... 100
guacamole  | selecting default shared_buffers ... 128MB
guacamole  | selecting default time zone ... Europe/Berlin
guacamole  | creating configuration files ... ok
guacamole  | running bootstrap script ... ok
guacamole  | performing post-bootstrap initialization ... ok
guacamole  | syncing data to disk ... ok
guacamole  |
guacamole  | initdb: warning: enabling "trust" authentication for local connections
guacamole  | You can change this by editing pg_hba.conf or using the option -A, or
guacamole  | --auth-local and --auth-host, the next time you run initdb.
guacamole  |
guacamole  | Success.
guacamole  |
guacamole  | waiting for server to start....2025-01-17 15:14:52.214 CET [63] LOG:  starting PostgreSQL 13.15 on x86_64-alpine-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
guacamole  | 2025-01-17 15:14:52.307 CET [63] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
guacamole  | 2025-01-17 15:14:52.316 CET [64] LOG:  database system was shut down at 2025-01-17 15:14:50 CET
guacamole  | 2025-01-17 15:14:52.324 CET [63] LOG:  database system is ready to accept connections
guacamole  |  done
guacamole  | server started
guacamole  | CREATE DATABASE
guacamole  |
guacamole  |
guacamole  | /usr/local/bin/_postgres.sh: ignoring /docker-entrypoint-initdb.d/*
guacamole  |
guacamole  | waiting for server to shut down...2025-01-17 15:14:53.063 CET [63] LOG:  received fast shutdown request
guacamole  | .2025-01-17 15:14:53.065 CET [63] LOG:  aborting any active transactions
guacamole  | 2025-01-17 15:14:53.068 CET [63] LOG:  background worker "logical replication launcher" (PID 70) exited with exit code 1
guacamole  | 2025-01-17 15:14:53.068 CET [65] LOG:  shutting down
guacamole  | 2025-01-17 15:14:53.093 CET [63] LOG:  database system is shut down
guacamole  |  done
guacamole  | server stopped
guacamole  |
guacamole  | PostgreSQL init process complete; ready for start up.
guacamole  |
guacamole  | 2025-01-17 15:14:53.198 CET [19] LOG:  starting PostgreSQL 13.15 on x86_64-alpine-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
guacamole  | 2025-01-17 15:14:53.198 CET [19] LOG:  listening on IPv6 address "::1", port 5432
guacamole  | 2025-01-17 15:14:53.198 CET [19] LOG:  listening on IPv4 address "127.0.0.1", port 5432
guacamole  | 2025-01-17 15:14:53.203 CET [19] LOG:  listening on Unix socket "/run/postgresql/.s.PGSQL.5432"
guacamole  | 2025-01-17 15:14:53.210 CET [78] LOG:  database system was shut down at 2025-01-17 15:14:53 CET
guacamole  | 2025-01-17 15:14:53.217 CET [19] LOG:  database system is ready to accept connections
guacamole  | Connection to localhost (::1) 5432 port [tcp/postgresql] succeeded!
guacamole  | database port open... Finishing Configuration
guacamole  | CREATE TYPE
guacamole  | CREATE TYPE
guacamole  | CREATE TYPE
guacamole  | CREATE TYPE
guacamole  | CREATE TYPE
guacamole  | CREATE TABLE
guacamole  | CREATE INDEX
guacamole  | CREATE TABLE
guacamole  | CREATE INDEX
guacamole  | CREATE TABLE
guacamole  | CREATE TABLE
guacamole  | CREATE TABLE
guacamole  | CREATE TABLE
guacamole  | CREATE TABLE
guacamole  | CREATE INDEX
guacamole  | CREATE TABLE
...
guacamole  | INSERT 0 1
guacamole  | INSERT 0 1
guacamole  | INSERT 0 6
guacamole  | INSERT 0 3
guacamole  | DB Preparation finished exiting for main processes...
guacamole  | 2025-01-17 15:14:54.260 CET [19] LOG:  received fast shutdown request
guacamole  | 2025-01-17 15:14:54.262 CET [19] LOG:  aborting any active transactions
guacamole  | 2025-01-17 15:14:54.265 CET [19] LOG:  background worker "logical replication launcher" (PID 84) exited with exit code 1
guacamole  | 2025-01-17 15:14:54.265 CET [79] LOG:  shutting down
guacamole  | 2025-01-17 15:14:54.464 CET [19] LOG:  database system is shut down
guacamole  | waiting for server to shut down.... done
guacamole  | server stopped
guacamole  | 2025-01-17 15:14:54,879 INFO Set uid to user 0 succeeded
guacamole  | 2025-01-17 15:14:54,885 INFO supervisord started with pid 1
guacamole  | 2025-01-17 15:14:55,887 INFO spawned: 'postgresql' with pid 97
guacamole  | 2025-01-17 15:14:55,890 INFO spawned: 'tomcat' with pid 98
guacamole  | 2025-01-17 15:14:55,893 INFO spawned: 'guacd' with pid 99
guacamole  | 2025-01-17 15:14:56,976 INFO success: postgresql entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
guacamole  | 2025-01-17 15:14:56,977 INFO success: tomcat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
guacamole  | 2025-01-17 15:14:56,977 INFO success: guacd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

```

Looks good and strange enough I can now log in using guacadmin:guacadmin 

I logged in and managed to change my password. Trying to change the profile of guacadmin I get an error:

![Image](https://github.com/user-attachments/assets/ff37a391-e068-4498-8e7a-bd5867e4c09f)

**I cannot even change this user's timezone.**
