### ISSUE TITLE
Suggestion: publish to ghcr.io registry

### ISSUE THREAD

**Issue by rcarmo** [flcontainers/guacamole#64]
Hi! I use your image and have been having trouble getting it from Docker Hub. I thought I'd share my workflow file that automatically builds and pushes to the GitHub registry using your own tokens:

```yaml
# .github/workflows/build-ghcr-docker-image.yml
name: Build Docker Image upon new tag

on:
  push:
    tags:
      - v*

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: . 
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository }}:latest
```
