### ISSUE TITLE
Adding to tomcat's server.xml

### ISSUE THREAD

**Issue by tscibilia** [flcontainers/guacamole#89]
I'm looking to modify the tomcat server.xml file to properly display the x-forwarded-for IP address of the client connection made to guacamole as described in the docs here https://guacamole.apache.org/doc/gug/reverse-proxy.html#setting-up-the-remote-ip-valve. Is there a convenient was to possible mount that file in the docker-compose file?

**Comment by Maksance** [comment]
This file is in /opt/tomcat/conf on the container side.
You can mount with these settings on your docker-compose:
```
version: "3"
services:
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      TZ: 'UTC'
      EXTENSIONS: 'auth-totp,auth-ldap'
    volumes:
      - postgres:/config
      - </path/to/your/directory>:/opt/tomcat/conf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
  postgres:
    driver: local
```
